BASE_URL = "https://the-internet.herokuapp.com"

ALERTS_URL = f"{BASE_URL}/javascript_alerts"
DOWNLOAD_URL = f"{BASE_URL}/download"
UPLOAD_URL = f"{BASE_URL}/upload"
FRAMES_URL = f"{BASE_URL}/nested_frames"
CONTEXT_MENU_URL = f"{BASE_URL}/context_menu"
SCROLL_URL = f"{BASE_URL}/infinite_scroll"
DYNAMIC_CONTENT_URL = f"{BASE_URL}/dynamic_content"
HORIZONTAL_URL = f"{BASE_URL}/horizontal_slider"
HOVERS_URL = f"{BASE_URL}/hovers"
LOGIN_URL = f"{BASE_URL}/basic_auth"
NEW_WINDOW_URL = f"{BASE_URL}/windows"
NEW_PAGE_URL = f"{BASE_URL}/windows/new"
